### ISSUE TITLE
New Feature Suggestion

### ISSUE THREAD

**Issue by SwiftyProgramme** [SwiftyProgrammer690/WPM-Tester-Java#2]
Maybe you should let java detect the errors somehow!

**Comment by SwiftyProgrammer690** [comment]
Yes, I am trying to do that but  I can't find a way how to...

**Comment by SwiftyProgrammer690** [comment]
I could instead of making an array of words, do an array of sentences and then let java check that instead of every word by one!

**Comment by SwiftyProgrammer690** [comment]
Noice

**Comment by SwiftyProgramme** [comment]
Nicely Done!

**Comment by SwiftyProgrammer690** [comment]
Yep!
