### ISSUE TITLE
Code not working even when typed correctly!

### ISSUE THREAD

**Issue by anonymouse-cmd** [SwiftyProgrammer690/WPM-Tester-Java#8]
So I tried to do this, and the feature that you have added might have broken!

**Comment by SwiftyProgrammer690** [comment]
I have made some changes to this while you were away...
Try `git pull` and see if that works!

**Comment by anonymouse-cmd** [comment]
No still not working!

**Comment by SwiftyProgrammer690** [comment]
I see the problem now, I am using deprecated unstable conditions!

**Comment by SwiftyProgrammer690** [comment]
I will fix src/WPMProgram.java!

**Comment by anonymouse-cmd** [comment]
oK!
